### ISSUE TITLE
Error when "bash scripts/run_xxx.sh"

### ISSUE THREAD

**Issue by KylinC** [raymin0223/fast_robust_early_exit#1]
AttributeError: 'T5Config' object has no attribute 'local_radius'

**Comment by KylinC** [comment]
Traceback (most recent call last):
  File "/hetu_group/chenqilin/fast_robust_early_exit/run_summarization.py", line 585, in <module>
    main(model_args, data_args, training_args, additional_args, model_cls, trainer_cls)
  File "/hetu_group/chenqilin/fast_robust_early_exit/run_summarization.py", line 230, in main
    model = model_cls.from_pretrained(
  File "/hetu_group/chenqilin/python_envs/datacomp/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2629, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/hetu_group/chenqilin/fast_robust_early_exit/models/modeling_longt5.py", line 515, in __init__
    super().__init__(config)
  File "/hetu_group/chenqilin/python_envs/datacomp/lib/python3.10/site-packages/transformers/models/longt5/modeling_longt5.py", line 1935, in __init__
    self.encoder = LongT5Stack(encoder_config, self.shared)
  File "/hetu_group/chenqilin/python_envs/datacomp/lib/python3.10/site-packages/transformers/models/longt5/modeling_longt5.py", line 1383, in __init__
    self.local_radius = config.local_radius
  File "/hetu_group/chenqilin/python_envs/datacomp/lib/python3.10/site-packages/transformers/configuration_utils.py", line 260, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'T5Config' object has no attribute 'local_radius'
Traceback (most recent call last):
  File "/hetu_group/chenqilin/fast_robust_early_exit/run_summarization.py", line 585, in <module>
    main(model_args, data_args, training_args, additional_args, model_cls, trainer_cls)
  File "/hetu_group/chenqilin/fast_robust_early_exit/run_summarization.py", line 230, in main
    model = model_cls.from_pretrained(
  File "/hetu_group/chenqilin/python_envs/datacomp/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2629, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/hetu_group/chenqilin/fast_robust_early_exit/models/modeling_longt5.py", line 515, in __init__
    super().__init__(config)
  File "/hetu_group/chenqilin/python_envs/datacomp/lib/python3.10/site-packages/transformers/models/longt5/modeling_longt5.py", line 1935, in __init__
    self.encoder = LongT5Stack(encoder_config, self.shared)
  File "/hetu_group/chenqilin/python_envs/datacomp/lib/python3.10/site-packages/transformers/models/longt5/modeling_longt5.py", line 1383, in __init__
    self.local_radius = config.local_radius
  File "/hetu_group/chenqilin/python_envs/datacomp/lib/python3.10/site-packages/transformers/configuration_utils.py", line 260, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'T5Config' object has no attribute 'local_radius'

**Comment by raymin0223** [comment]
Hi @KylinC,

Thanks for the interest in our paper and sorry for the bugs. 
I guess that you are running Bigpatent or Multi-news datasets because `local_radius` attribute belongs to LongT5Config.

But, I found that there are typos in our script files. 
You have to change to `--model_name_or_path google/long-t5-tglobal-base` in `run_sum_bigpatent.sh` and `run_sum_multinews.sh`.
