### ISSUE TITLE
Question: how can I run 2 instances simultanously? 

### ISSUE THREAD

**Issue by Sunt-ing** [raymin0223/fast_robust_early_exit#14]
Currently, I run the model in a single GPU setting, but actually I have multiple GPUs in the machine, so I am thinking about how can I run multiple instances together. 
e.g.

instance 1:
```
CUDA_VISIBLE_DEVICES=1 nohup python -m torch.distributed.run --nproc_per_node=1 \
    run_summarization.py \
    --model_name_or_path ./save/cnndm_t5_large/ \
    --do_eval \
    --dataset_name cnn_dailymail \
    --dataset_config_name "3.0.0" \
    --output_dir ./res/cnndm_t5_large_1/ \
    --per_device_eval_batch_size 1 \
    --deploy_scenario True \
    --use_synchronize True \
    --overwrite_output_dir \
    --predict_with_generate \
    --source_prefix "summarize: "
```

instance2:
```
CUDA_VISIBLE_DEVICES=2 nohup python -m torch.distributed.run --nproc_per_node=1 \
    run_summarization.py \
    --model_name_or_path ./save/cnndm_t5_large/ \
    --do_eval \
    --dataset_name cnn_dailymail \
    --dataset_config_name "3.0.0" \
    --output_dir ./res/cnndm_t5_large_2/ \
    --per_device_eval_batch_size 1 \
    --deploy_scenario True \
    --use_synchronize True \
    --overwrite_output_dir \
    --predict_with_generate \
    --source_prefix "summarize: "
```

I guess that I may need to explicitly assign the port to my second instance, but I am not sure how and whether that's all I need to do.

Thank!

**Comment by raymin0223** [comment]
Hi @Sunt-ing, 

As I understand, you want to run a single GPU evaluation experiment, but multiple experiments simultaneously with multi-GPUs.    
If yes, your guess looks correct. Because we assign different GPUs for each experiment, only thing left is giving different `master_port` I believe.  

So, let me know after changing the command to `CUDA_VISIBLE_DEVICES=1 nohup python -m torch.distributed.run --nproc_per_node=1 --master_port 29501 (or sth else) \`.

**Comment by Sunt-ing** [comment]
```txt
Traceback (most recent call last):
  File "/local/scratch/f/xiaoze/fast_robust_early_exit/run_summarization.py", line 571, in <module>
    model_args, data_args, training_args, additional_args = parser.parse_args_into_dataclasses()
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--master_port', '12003']
[2024-06-17 21:42:23,159] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2269822) of binary: /local/scratch/e/xiaoze/miniconda3/envs/free/bin/python
Traceback (most recent call last):
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_summarization.py FAILED

```

**Comment by raymin0223** [comment]
What was the command? I don't get it why `master_port` is given to HfArgumentParaser.

**Comment by Sunt-ing** [comment]
Oh, I passed it to the python file. That's the problem. Fixed. Thanks you!

**Comment by raymin0223** [comment]
Sounds great!! It looks like that haha. Thanks for your interests :)
